CREATE TABLE training_requests (
id INT PRIMARY KEY AUTO_INCREMENT,
employee_id VARCHAR(20) NOT NULL,
employee_name VARCHAR(100) NOT NULL,
training_title VARCHAR(200) NOT NULL,
training_description TEXT NOT NULL,
requested_date DATE NOT NULL,
status ENUM('PENDING','APPROVED', 'REJECTED') NOT NULL DEFAULT "PENDING",
manager_id VARCHAR(20) NOT NULL,
last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);