# print("hello world")
# print("\\hello world\\")
# print("hello\rworld") 
# a=input("enter the number")
# print(type(a))
# print("taniya \\ singh")
name = input("enter your name:")
age = int(input("enter your age:"))
salary = float(input("enter your salary:"))
print(f"name: {name}, age: {age}, salary: {salary}")