from pydantic import BaseModel, field_validator, EmailStr
import re

class VendorMaster(BaseModel):
    # Vendor ID: A unique identifier for the vendor, typically auto-generated by the database
    vendor_id: int
    
    # Vendor name: The name of the vendor, only alphabets and spaces allowed, up to 100 characters
    vendor_name: str
    
    # Contact person: The name of the person who can be contacted at the vendor's end, only alphabets and spaces allowed
    contact_person: str
    
    # Contact phone: The contact phone number of the vendor's representative, should be a valid 10-digit Indian mobile number
    contact_phone: str
    
    # GST number: The GST number of the vendor, must be exactly 15 characters (alphanumeric)
    gst_number: str
    
    # Email: The email address of the vendor, validated using the `EmailStr` type from Pydantic for correct email format
    email: EmailStr
    
    # Address: The physical address of the vendor, cannot exceed 200 characters
    address: str
    
    # City: The city in which the vendor is located (not validated here, assumed to be valid based on input)
    city: str
    
    # Active status: Indicates whether the vendor is currently active or inactive, must be one of the two values: "Active" or "Inactive"
    active_status: str

    # Validator for vendor_name: Ensures the vendor name contains only alphabets and spaces, with a maximum length of 100 characters
    @field_validator("vendor_name")
    def vendor_name_valid(cls, v):
        if not re.fullmatch(r"[A-Za-z ]{1,100}", v):
            raise ValueError("vendor_name must be alphabets only")
        return v

    # Validator for contact_person: Ensures the contact person's name contains only alphabets and spaces, with a maximum length of 100 characters
    @field_validator("contact_person")
    def contact_person_valid(cls, v):
        if not re.fullmatch(r"[A-Za-z ]{1,100}", v):
            raise ValueError("contact_person must be alphabets only")
        return v

    # Validator for contact_phone: Ensures the phone number is a valid Indian mobile number (10 digits, starting with 6-9)
    @field_validator("contact_phone")
    def phone_valid(cls, v):
        if not re.fullmatch(r"[6-9]\d{9}", v):
            raise ValueError("Invalid Indian mobile number")
        return v

    # Validator for gst_number: Ensures the GST number is exactly 15 alphanumeric characters (standard format)
    @field_validator("gst_number")
    def gst_valid(cls, v):
        if not re.fullmatch(r"[A-Za-z0-9]{15}", v):
            raise ValueError("Invalid GST number")
        return v

    # Validator for address: Ensures the address length does not exceed 200 characters
    @field_validator("address")
    def address_length(cls, v):
        if len(v) > 200:
            raise ValueError("Address too long")
        return v

    # Validator for active_status: Ensures the status is either "Active" or "Inactive"
    @field_validator("active_status")
    def status_valid(cls, v):
        if v not in {"Active", "Inactive"}:
            raise ValueError("active_status must be Active or Inactive")
        return v
