CREATE TABLE `asset_inventory` (
  `ASSET_ID` int NOT NULL AUTO_INCREMENT,
  `ASSET_TAG` varchar(50) NOT NULL,
  `ASSET_TYPE` varchar(50) NOT NULL,
  `SERIAL_NUMBER` varchar(100) NOT NULL,
  `MANUFACTURER` varchar(50) NOT NULL,
  `MODEL` varchar(100) NOT NULL,
  `PURCHASE_DATE` date NOT NULL,
  `WARRANTY_YEARS` int NOT NULL,
  `ASSIGNED_TO` varchar(100) DEFAULT NULL,
  `ASSET_STATUS` varchar(20) NOT NULL,
  `LAST_UPDATED` datetime NOT NULL,
  PRIMARY KEY (`ASSET_ID`),
  UNIQUE KEY `ASSET_TAG_UNIQUE` (`ASSET_TAG`),
  UNIQUE KEY `SERIAL_NUMBER_UNIQUE` (`SERIAL_NUMBER`)
);
