import csv
 
# 1. Read ust_healthcare_visits.csv with csv.DictReader.
 
with open("ust_healthcare_visits.csv", "r", encoding="utf-8") as file:
    print("Data Present in ust_healthcare_visits.csv:\n")
    csv_reader = csv.DictReader(file)
    for row in csv_reader:
        print(row)
 
 
# 2. Basic validation / normalization:
# Required fields: patient_id, name, visit_date, billed_amount, payment_status.
# If any missing → skip that row (and print a short message).
# Convert billed_amount to float (if conversion fails, skip row).
# Trim whitespace from string fields.
# Normalize payment_status to Title case (e.g., "pending" → "Pending").
# Normalize follow_up_required to "Yes" or "No" (treat empty as "No").
 
count = {"skipped": 0, "total": 0, "processed": 0}
cleaned_rows = []
 
required_fields = ["patient_id", "name", "visit_date", "billed_amount", "payment_status"]
 
with open("ust_healthcare_visits.csv", "r", encoding="ISO-8859-1") as file:
    csv_reader = csv.DictReader(file)
 
    for row in csv_reader:
        count["total"] += 1
        row = {key: val.strip() for key, val in row.items() if val is not None}
 
        # Skip rows with missing required fields
        if not all(row.get(field) for field in required_fields):
            print("Skipping row due to missing required fields:", row)
            count["skipped"] += 1
            continue
 
        # Convert billed_amount to float safely
        try:
            row["billed_amount"] = float(row["billed_amount"])
        except ValueError:
            print("Invalid billed_amount:", row["billed_amount"], "for patient:", row["patient_id"])
            count["skipped"] += 1
            continue
 
        # Normalize payment_status
        row["payment_status"] = row["payment_status"].title()
 
        # Normalize follow_up_required
        row["follow_up_required"] = "Yes" if row.get("follow_up_required", "").strip() else "No"
 
        # Clean name, patient_id, etc.
        row["name"] = row["name"].strip()
        row["patient_id"] = row["patient_id"].strip()
 
        cleaned_rows.append(row)
        count["processed"] += 1
 
print("\nData Cleaning Completed Successfully!\n")
 
 
# 3. Create outputs:
# pending_payments.csv : all cleaned columns for rows where payment_status != "Paid".
# patient_summary.csv : aggregated per patient_id with columns:
# patient_id, name, total_visits, total_billed, has_pending_payment.
# total_billed formatted with 2 decimals (e.g., 7500.00).
# has_pending_payment = "Yes" if any visit for that patient is not Paid; otherwise "No".
 
# Filter pending payments
pending = [r for r in cleaned_rows if r["payment_status"] != "Paid"]
 
# Write pending_payments.csv
if pending:
    with open("pending_payments.csv", "w", newline="", encoding="ISO-8859-1") as file:
        writer = csv.DictWriter(file, fieldnames=cleaned_rows[0].keys())
        writer.writeheader()
        writer.writerows(pending)
    print("pending_payments.csv created successfully.")
else:
    print("No pending payments found.")
 
# Create patient summary
summary = {}
for row in cleaned_rows:
    pid = row["patient_id"]
    if pid not in summary:
        summary[pid] = {
            "name": row["name"],
            "total_visits": 0,
            "total_billed": 0.0,
            "has_pending_payment": "No",
        }
    summary[pid]["total_visits"] += 1
    summary[pid]["total_billed"] += row["billed_amount"]
    if row["payment_status"] != "Paid":
        summary[pid]["has_pending_payment"] = "Yes"
 
# Write patient_summary.csv
with open("patient_summary.csv", "w", newline="", encoding="ISO-8859-1") as file:
    header = ["patient_id", "name", "total_visits", "total_billed", "has_pending_payment"]
    writer = csv.DictWriter(file, fieldnames=header)
    writer.writeheader()
    for pid, val in summary.items():
        val["total_billed"] = f"{val['total_billed']:.2f}"
        row = {"patient_id": pid, **val}
        writer.writerow(row)
 
print("patient_summary.csv created successfully.")
 
 
# 4. Console summary: print counts
 
print("\n--- Summary Report ---")
print("Total rows read:", count["total"])
print("Processed rows:", count["processed"])
print("Skipped rows:", count["skipped"])
print("Pending payments:", len(pending))
print("Patient summary rows:", len(summary))

# ----------------------------------------------------------------------------------------

# Sample Output

# Data Present in ust_healthcare_visits.csv:

# {'patient_id': 'P001', 'name': 'Arun Kumar', 'dob': '1985-04-12', 'gender': 'M', 'contact': '9810012345', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-01', 'visit_type': 'OP', 'diagnosis_codes': ' I20.9 ; E11.9 ', 'procedure_codes': ' PROC1001; PROC1002', 'billed_amount': '7500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1001', 'payment_status': 'Paid', 'discharge_date': '2025-10-01', 'follow_up_required': 'Yes', 'notes': 'Patient stable. Advised follow-up in 2 weeks.'}
# {'patient_id': 'P002', 'name': 'Riya Sharma', 'dob': '1990-07-30', 'gender': 'F', 'contact': '9810098765', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-02', 'visit_type': 'IP', 'diagnosis_codes': 'E66.9', 'procedure_codes': 'PROC2001', 'billed_amount': '12000.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2002', 'payment_status': 'Pending', 'discharge_date': '2025-10-05', 'follow_up_required': 'No', 'notes': 'Surgery performed. Observe for fever.'}
# {'patient_id': 'P003', 'name': 'John Doe', 'dob': '1978-01-05', 'gender': 'M', 'contact': '8800123456', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-02', 'visit_type': 'OP', 'diagnosis_codes': 'G40.9', 'procedure_codes': ' ', 'billed_amount': '3500.00', 'insurance_provider': '', 'insurance_id': ' ', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'First visit; intermittent headaches.'}
# {'patient_id': 'P004', 'name': 'Meena Patel', 'dob': '2001-12-11', 'gender': 'F', 'contact': '7700123456', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-03', 'visit_type': 'OP', 'diagnosis_codes': 'I10', 'procedure_codes': 'PROC1003', 'billed_amount': '2200.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1004', 'payment_status': 'Paid', 'discharge_date': '2025-10-03', 'follow_up_required': 'No', 'notes': 'BP elevated; medication started.'}
# {'patient_id': 'P005', 'name': 'Suresh K', 'dob': '1965-03-23', 'gender': 'M', 'contact': '9900112233', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-03', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '1800.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3001', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Diabetes review; missing labs.'}
# {'patient_id': 'P006', 'name': 'Neha Verma', 'dob': '1988-09-17', 'gender': 'F', 'contact': '9600001111', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-04', 'visit_type': 'OP', 'diagnosis_codes': 'H90.3', 'procedure_codes': 'PROC5001', 'billed_amount': '4800.50', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4002', 'payment_status': 'Paid', 'discharge_date': '2025-10-04', 'follow_up_required': 'No', 'notes': 'Ear cleaning; tinnitus complaint.'}
# {'patient_id': 'P007', 'name': 'Alex Johnson', 'dob': '1995-11-11', 'gender': 'M', 'contact': '7000005555', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-04', 'visit_type': 'OP', 'diagnosis_codes': 'G43.0', 'procedure_codes': 'PROC3002; PROC3003', 'billed_amount': '6000.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5001', 'payment_status': 'Pending', 'discharge_date': '2025-10-04', 'follow_up_required': 'Yes', 'notes': 'Migraine; MRI recommended.'}
# {'patient_id': 'P008', 'name': 'Li Wei', 'dob': '1970-06-06', 'gender': 'M', 'contact': '6000012345', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-05', 'visit_type': 'IP', 'diagnosis_codes': 'C34.9', 'procedure_codes': 'PROC6001; PROC6002', 'billed_amount': '45000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6001', 'payment_status': 'Paid', 'discharge_date': '2025-10-20', 'follow_up_required': 'Yes', 'notes': 'Chemo cycle; extended stay.'}
# {'patient_id': 'P009', 'name': 'Anita Singh', 'dob': '1982-02-02', 'gender': 'F', 'contact': '8800099999', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-05', 'visit_type': 'OP', 'diagnosis_codes': 'J00', 'procedure_codes': ' ', 'billed_amount': '900.00', 'insurance_provider': '', 'insurance_id': ' ', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Cold symptoms; OTC advised.'}
# {'patient_id': 'P010', 'name': 'Michael Brown', 'dob': '2004-08-21', 'gender': 'M', 'contact': '7700012345', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-06', 'visit_type': 'OP', 'diagnosis_codes': 'A09', 'procedure_codes': 'PROC7001', 'billed_amount': '1500.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7001', 'payment_status': 'Paid', 'discharge_date': '2025-10-06', 'follow_up_required': 'No', 'notes': 'Pediatric exam; immunizations updated.'}
# {'patient_id': 'P011', 'name': 'Sophia Lee', 'dob': '1999-05-14', 'gender': 'F', 'contact': '7700011111', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-06', 'visit_type': 'OP', 'diagnosis_codes': 'I25.10', 'procedure_codes': 'PROC1004', 'billed_amount': '5200.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1002', 'payment_status': 'Pending', 'discharge_date': '2025-10-06', 'follow_up_required': 'Yes', 'notes': 'Angina; stress test scheduled.'}
# {'patient_id': 'P012', 'name': 'Rajesh Kumar', 'dob': '1955-11-25', 'gender': 'M', 'contact': '7700012222', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-07', 'visit_type': 'IP', 'diagnosis_codes': 'I50.9', 'procedure_codes': 'PROC4001; PROC4002', 'billed_amount': '16000.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3004', 'payment_status': 'Paid', 'discharge_date': '2025-10-10', 'follow_up_required': 'Yes', 'notes': 'Heart failure care; vitals monitoring.'}
# {'patient_id': 'P013', 'name': 'Olga Petrova', 'dob': '1983-03-03', 'gender': 'F', 'contact': '7700013333', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-10-07', 'visit_type': 'OP', 'diagnosis_codes': 'E03.9', 'procedure_codes': ' ', 'billed_amount': '4200.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8001', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Thyroid abnormal; Rx started.'}
# {'patient_id': 'P014', 'name': 'Diego Marquez', 'dob': '1992-10-10', 'gender': 'M', 'contact': '8800066666', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-08', 'visit_type': 'OP', 'diagnosis_codes': 'S72.0', 'procedure_codes': 'PROC2002', 'billed_amount': '7000.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2003', 'payment_status': 'Paid', 'discharge_date': '2025-10-08', 'follow_up_required': 'No', 'notes': 'Fracture follow-up; cast removal.'}
# {'patient_id': 'P015', 'name': 'Ananya Rao', 'dob': '2007-04-04', 'gender': 'F', 'contact': '8800044444', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-08', 'visit_type': 'OP', 'diagnosis_codes': 'R50.9', 'procedure_codes': ' ', 'billed_amount': '1100.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7002', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Fever; advised rest.'}
# {'patient_id': 'P016', 'name': 'Sunil Sharma', 'dob': '1980-09-10', 'gender': 'M', 'contact': '+91-98 100 12345', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-09', 'visit_type': 'OP', 'diagnosis_codes': 'I20.9', 'procedure_codes': 'PROC1005', 'billed_amount': '8200.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1003', 'payment_status': 'Paid', 'discharge_date': '2025-10-09', 'follow_up_required': 'Yes', 'notes': 'Post-angina follow-up.'}
# {'patient_id': 'P017', 'name': 'Leila Ahmed', 'dob': '1994-02-14', 'gender': 'F', 'contact': '98100-22233', 'provider_id': 'DR900', 'provider_name': 'Dr. Narayan', 'department': 'Dermatology', 'visit_date': '2025-10-09', 'visit_type': 'OP', 'diagnosis_codes': 'L20.8', 'procedure_codes': ' ', 'billed_amount': '600.00', 'insurance_provider': 'DermiCare', 'insurance_id': 'INS9001', 'payment_status': 'unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Eczema; topical treatment.'}
# {'patient_id': 'P018', 'name': 'Peter Clark', 'dob': '1969-12-31', 'gender': 'M', 'contact': '98000 33344', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-10', 'visit_type': 'OP', 'diagnosis_codes': 'G93.1', 'procedure_codes': 'PROC3004', 'billed_amount': '4300.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5002', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Dizziness evaluation.'}
# {'patient_id': 'P019', 'name': 'Maya Singh', 'dob': '1987-08-08', 'gender': 'F', 'contact': '9990012345', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-10', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '2100.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3002', 'payment_status': 'Paid', 'discharge_date': '2025-10-10', 'follow_up_required': 'No', 'notes': 'Diabetes counseling.'}
# {'patient_id': 'P020', 'name': 'Oscar Wilde', 'dob': '1973-05-16', 'gender': 'M', 'contact': '7700098888', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-11', 'visit_type': 'IP', 'diagnosis_codes': 'C50.9', 'procedure_codes': 'PROC6003; PROC6004', 'billed_amount': '36000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6002', 'payment_status': 'Paid', 'discharge_date': '2025-10-18', 'follow_up_required': 'Yes', 'notes': 'Surgery & chemo plan.'}
# {'patient_id': 'P021', 'name': 'Lina Gomez', 'dob': '1991-01-01', 'gender': 'F', 'contact': '7700097777', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-11', 'visit_type': 'OP', 'diagnosis_codes': 'H66.9', 'procedure_codes': 'PROC5002', 'billed_amount': '2500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4003', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Otitis media; antibiotics.'}
# {'patient_id': 'P022', 'name': 'Tom Hanks', 'dob': '1956-07-09', 'gender': 'M', 'contact': '8800088888', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-12', 'visit_type': 'OP', 'diagnosis_codes': 'G40.9', 'procedure_codes': ' ', 'billed_amount': '5000.00', 'insurance_provider': '', 'insurance_id': ' ', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Seizure history; follow-up.'}
# {'patient_id': 'P023', 'name': 'Sana Khan', 'dob': '2002-03-05', 'gender': 'F', 'contact': '7700022222', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-10-12', 'visit_type': 'OP', 'diagnosis_codes': 'E11.65', 'procedure_codes': ' ', 'billed_amount': '3200.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8002', 'payment_status': 'Paid', 'discharge_date': '2025-10-12', 'follow_up_required': 'No', 'notes': 'Diabetes follow-up.'}
# {'patient_id': 'P024', 'name': 'Raj Patel', 'dob': '1984-06-06', 'gender': 'M', 'contact': ' +91-77 000 33333 ', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-12', 'visit_type': 'OP', 'diagnosis_codes': 'M54.5', 'procedure_codes': 'PROC2003', 'billed_amount': '4100.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2004', 'payment_status': 'PENDING', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Back pain; physio advised.'}
# {'patient_id': 'P025', 'name': 'Emily Stone', 'dob': '1998-11-11', 'gender': 'F', 'contact': '7000011111', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-13', 'visit_type': 'OP', 'diagnosis_codes': 'J06.9', 'procedure_codes': ' ', 'billed_amount': '900.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7003', 'payment_status': 'Paid', 'discharge_date': '2025-10-13', 'follow_up_required': 'No', 'notes': 'Cold symptoms.'}
# {'patient_id': 'P026', 'name': 'Victor Hugo', 'dob': '1960-02-02', 'gender': 'M', 'contact': '7700044444', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-13', 'visit_type': 'OP', 'diagnosis_codes': 'I48.1', 'procedure_codes': 'PROC1006', 'billed_amount': '9800.75', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1005', 'payment_status': 'Pending', 'discharge_date': '2025-10-14', 'follow_up_required': 'Yes', 'notes': 'Atrial fibrillation consult.'}
# {'patient_id': 'P027', 'name': 'Zara Ali', 'dob': '1993-09-09', 'gender': 'F', 'contact': '8800055555', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-14', 'visit_type': 'OP', 'diagnosis_codes': 'J45.9', 'procedure_codes': ' ', 'billed_amount': '1400.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3003', 'payment_status': 'Paid', 'discharge_date': '2025-10-14', 'follow_up_required': 'No', 'notes': 'Asthma review.'}
# {'patient_id': 'P028', 'name': 'Ken Watanabe', 'dob': '1970-03-21', 'gender': 'M', 'contact': '60000-22222', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-14', 'visit_type': 'IP', 'diagnosis_codes': 'C61.9', 'procedure_codes': 'PROC6005', 'billed_amount': '22000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6003', 'payment_status': 'Paid', 'discharge_date': '2025-10-17', 'follow_up_required': 'Yes', 'notes': 'Prostate surgery.'}
# {'patient_id': 'P029', 'name': 'Liu Chen', 'dob': '1985-08-08', 'gender': 'M', 'contact': '6000012222', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-15', 'visit_type': 'OP', 'diagnosis_codes': 'H90.3', 'procedure_codes': 'PROC5003; PROC5004', 'billed_amount': '5200.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4004', 'payment_status': 'Pending', 'discharge_date': '2025-10-15', 'follow_up_required': 'Yes', 'notes': 'Hearing test and minor procedure.'}
# {'patient_id': 'P030', 'name': 'Mira Kapoor', 'dob': '1996-12-12', 'gender': 'F', 'contact': '7700066666', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-10-15', 'visit_type': 'OP', 'diagnosis_codes': 'E66.9', 'procedure_codes': ' ', 'billed_amount': '3000.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8003', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Obesity counseling.'}
# {'patient_id': 'P031', 'name': 'Sam Wilson', 'dob': '1989-05-05', 'gender': 'M', 'contact': '8800022222', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-16', 'visit_type': 'OP', 'diagnosis_codes': 'G43.1', 'procedure_codes': 'PROC3005', 'billed_amount': '6100.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5003', 'payment_status': 'pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Chronic migraine management.'}
# {'patient_id': 'P032', 'name': 'Isha Verma', 'dob': '2000-04-20', 'gender': 'F', 'contact': '9900099999', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-16', 'visit_type': 'OP', 'diagnosis_codes': 'R53.1', 'procedure_codes': ' ', 'billed_amount': '800.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3005', 'payment_status': 'Paid', 'discharge_date': '2025-10-16', 'follow_up_required': 'No', 'notes': 'Fatigue; labs ordered.'}
# {'patient_id': 'P033', 'name': 'Arjun Singh', 'dob': '1977-07-07', 'gender': 'M', 'contact': '98100 77788', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-17', 'visit_type': 'OP', 'diagnosis_codes': 'I21.3', 'procedure_codes': 'PROC1007', 'billed_amount': '14500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1006', 'payment_status': 'Paid', 'discharge_date': '2025-10-17', 'follow_up_required': 'Yes', 'notes': 'Acute MI care; discharge planned.'}
# {'patient_id': 'P034', 'name': 'Nora Bates', 'dob': '1992-02-28', 'gender': 'F', 'contact': '7700077777', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-17', 'visit_type': 'OP', 'diagnosis_codes': 'A02.1', 'procedure_codes': ' ', 'billed_amount': '1300.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7004', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Gastroenteritis; hydration advised.'}
# {'patient_id': 'P035', 'name': 'Paul Green', 'dob': '1966-10-10', 'gender': 'M', 'contact': '8800012345', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-18', 'visit_type': 'OP', 'diagnosis_codes': 'S82.0', 'procedure_codes': 'PROC2004', 'billed_amount': '5400.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2005', 'payment_status': 'Paid', 'discharge_date': '2025-10-18', 'follow_up_required': 'No', 'notes': 'Ankle fracture clinic.'}
# {'patient_id': 'P036', 'name': 'Farah Khan', 'dob': '1988-11-11', 'gender': 'F', 'contact': '7700088888', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-18', 'visit_type': 'OP', 'diagnosis_codes': 'H92.0', 'procedure_codes': ' ', 'billed_amount': '2900.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4005', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Tinnitus workup.'}
# {'patient_id': 'P037', 'name': 'Igor Petrov', 'dob': '1959-09-09', 'gender': 'M', 'contact': '7700090000', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-19', 'visit_type': 'IP', 'diagnosis_codes': 'C34.9', 'procedure_codes': 'PROC6006; PROC6007', 'billed_amount': '52000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6004', 'payment_status': 'Paid', 'discharge_date': '2025-10-26', 'follow_up_required': 'Yes', 'notes': 'Lung cancer complex care.'}
# {'patient_id': 'P038', 'name': 'Karen Mills', 'dob': '1975-06-06', 'gender': 'F', 'contact': '7000023334', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-19', 'visit_type': 'OP', 'diagnosis_codes': 'E78.5', 'procedure_codes': ' ', 'billed_amount': '1700.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3006', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Hyperlipidemia follow-up.'}
# {'patient_id': 'P039', 'name': 'Yuki Tanaka', 'dob': '1984-08-08', 'gender': 'F', 'contact': '6000034444', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-19', 'visit_type': 'OP', 'diagnosis_codes': 'G93.3', 'procedure_codes': 'PROC3006', 'billed_amount': '4700.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5004', 'payment_status': 'Paid', 'discharge_date': '2025-10-19', 'follow_up_required': 'No', 'notes': 'Neuropathy evaluation.'}
# {'patient_id': 'P040', 'name': 'Rachel Adams', 'dob': '1997-01-15', 'gender': 'F', 'contact': '7700035555', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-10-20', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '4100.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8004', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Diabetes meds adjusted.'}
# {'patient_id': 'P041', 'name': 'Dev Patel', 'dob': '1999-09-09', 'gender': 'M', 'contact': '98100-11122', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-20', 'visit_type': 'OP', 'diagnosis_codes': 'M25.5', 'procedure_codes': ' ', 'billed_amount': '2300.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2006', 'payment_status': 'Paid', 'discharge_date': '2025-10-20', 'follow_up_required': 'No', 'notes': 'Knee pain; injections planned.'}
# {'patient_id': 'P042', 'name': 'Sofia Loren', 'dob': '1934-09-20', 'gender': 'F', 'contact': '7700001112', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-20', 'visit_type': 'IP', 'diagnosis_codes': 'I50.9', 'procedure_codes': 'PROC1008', 'billed_amount': '18500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1007', 'payment_status': 'Paid', 'discharge_date': '2025-10-25', 'follow_up_required': 'Yes', 'notes': 'Heart failure inpatient.'}
# {'patient_id': 'P043', 'name': 'Imran Khan', 'dob': '1982-12-12', 'gender': 'M', 'contact': '8800077777', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-21', 'visit_type': 'OP', 'diagnosis_codes': 'J11.1', 'procedure_codes': ' ', 'billed_amount': '900.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3007', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Flu symptoms.'}
# {'patient_id': 'P044', 'name': 'Linda Park', 'dob': '1990-06-06', 'gender': 'F', 'contact': '7000066666', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-21', 'visit_type': 'OP', 'diagnosis_codes': 'H74.3', 'procedure_codes': 'PROC5005', 'billed_amount': '3100.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4006', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Ear surgery follow-up.'}
# {'patient_id': 'P045', 'name': 'Noah Brown', 'dob': '2003-03-03', 'gender': 'M', 'contact': '7700047777', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-21', 'visit_type': 'OP', 'diagnosis_codes': 'A15.0', 'procedure_codes': ' ', 'billed_amount': '2000.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7005', 'payment_status': 'Paid', 'discharge_date': '2025-10-21', 'follow_up_required': 'No', 'notes': 'TB test positive; refer.'}
# {'patient_id': 'P046', 'name': 'Nadia Petrova', 'dob': '1986-04-04', 'gender': 'F', 'contact': '7700048888', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-10-22', 'visit_type': 'OP', 'diagnosis_codes': 'E03.9', 'procedure_codes': 'PROC8001', 'billed_amount': '4500.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8005', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Thyroid injection given.'}
# {'patient_id': 'P047', 'name': 'Oscar Diaz', 'dob': '1978-05-05', 'gender': 'M', 'contact': '8800031111', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-22', 'visit_type': 'OP', 'diagnosis_codes': 'S52.5', 'procedure_codes': 'PROC2005; PROC2006', 'billed_amount': '8000.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2007', 'payment_status': 'Paid', 'discharge_date': '2025-10-22', 'follow_up_required': 'Yes', 'notes': 'Forearm fracture ORIF.'}
# {'patient_id': 'P048', 'name': 'Helena Costa', 'dob': '1991-07-07', 'gender': 'F', 'contact': '7700023333', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-22', 'visit_type': 'OP', 'diagnosis_codes': 'G40.4', 'procedure_codes': ' ', 'billed_amount': '2600.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5005', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Epilepsy med review.'}
# {'patient_id': 'P049', 'name': 'Manish Malhotra', 'dob': '1968-11-11', 'gender': 'M', 'contact': '9900091111', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-23', 'visit_type': 'OP', 'diagnosis_codes': 'I25.9', 'procedure_codes': 'PROC1009', 'billed_amount': '12500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1008', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Stable angina; cath planned.'}
# {'patient_id': 'P050', 'name': 'Eva Green', 'dob': '1987-01-22', 'gender': 'F', 'contact': '7700055555', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-23', 'visit_type': 'IP', 'diagnosis_codes': 'C61.9', 'procedure_codes': 'PROC6008', 'billed_amount': '28000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6005', 'payment_status': 'Paid', 'discharge_date': '2025-11-02', 'follow_up_required': 'Yes', 'notes': 'Surgical oncology.'}
# {'patient_id': 'P051', 'name': 'Samir Das', 'dob': '1972-02-02', 'gender': 'M', 'contact': '9810022222', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-23', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '1900.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3008', 'payment_status': 'Paid', 'discharge_date': '2025-10-23', 'follow_up_required': 'No', 'notes': 'Routine diabetes check.'}
# {'patient_id': 'P052', 'name': 'Priya Menon', 'dob': '1995-05-05', 'gender': 'F', 'contact': '7700061111', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-24', 'visit_type': 'OP', 'diagnosis_codes': 'H65.1', 'procedure_codes': 'PROC5006', 'billed_amount': '2700.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4007', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Otitis externa therapy.'}
# {'patient_id': 'P053', 'name': 'Andrei Ivanov', 'dob': '1980-12-12', 'gender': 'M', 'contact': '7700062222', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-24', 'visit_type': 'OP', 'diagnosis_codes': 'G93.1', 'procedure_codes': ' ', 'billed_amount': '4100.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5006', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Headache; MRI recommended.'}
# {'patient_id': 'P054', 'name': 'Lucy Hale', 'dob': '1993-08-08', 'gender': 'F', 'contact': '7000033333', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-24', 'visit_type': 'OP', 'diagnosis_codes': 'A08.0', 'procedure_codes': ' ', 'billed_amount': '1100.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7006', 'payment_status': 'Paid', 'discharge_date': '2025-10-24', 'follow_up_required': 'No', 'notes': 'Viral gastroenteritis.'}
# {'patient_id': 'P055', 'name': 'Deepak Yadav', 'dob': '1989-09-09', 'gender': 'M', 'contact': '8800023333', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-25', 'visit_type': 'OP', 'diagnosis_codes': 'M16.5', 'procedure_codes': 'PROC2007', 'billed_amount': '7200.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2008', 'payment_status': 'Paid', 'discharge_date': '2025-10-25', 'follow_up_required': 'Yes', 'notes': 'Hip pain; plan arthroscopy.'}
# {'patient_id': 'P056', 'name': 'Helga Schmidt', 'dob': '1976-10-10', 'gender': 'F', 'contact': '6000044444', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-25', 'visit_type': 'IP', 'diagnosis_codes': 'C18.9', 'procedure_codes': 'PROC6009; PROC6010', 'billed_amount': '39000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6006', 'payment_status': 'PENDING', 'discharge_date': '2025-10-30', 'follow_up_required': 'Yes', 'notes': 'Colon surgery.'}
# {'patient_id': 'P057', 'name': 'Karan Johar', 'dob': '1970-05-05', 'gender': 'M', 'contact': '7700081111', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-25', 'visit_type': 'OP', 'diagnosis_codes': 'I20.0', 'procedure_codes': ' ', 'billed_amount': '4500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1009', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Stable angina; meds.'}
# {'patient_id': 'P058', 'name': 'Mayra Lopez', 'dob': '1998-06-06', 'gender': 'F', 'contact': '7700082222', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-26', 'visit_type': 'OP', 'diagnosis_codes': 'R10.9', 'procedure_codes': ' ', 'billed_amount': '900.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3009', 'payment_status': 'Paid', 'discharge_date': '2025-10-26', 'follow_up_required': 'No', 'notes': 'Abdominal pain; USG ordered.'}
# {'patient_id': 'P059', 'name': 'Daniel Craig', 'dob': '1969-03-02', 'gender': 'M', 'contact': '7700093333', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-26', 'visit_type': 'OP', 'diagnosis_codes': 'H92.1', 'procedure_codes': 'PROC5007', 'billed_amount': '3300.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4010', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Post-op check.'}
# {'patient_id': 'P060', 'name': 'Ayesha Khan', 'dob': '1992-09-09', 'gender': 'F', 'contact': '7700094444', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-10-26', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '4200.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8006', 'payment_status': 'paid', 'discharge_date': '2025-10-26', 'follow_up_required': 'No', 'notes': 'Diabetes follow-up.'}
# {'patient_id': 'P061', 'name': 'Boris Becker', 'dob': '1967-06-06', 'gender': 'M', 'contact': '8800045555', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-27', 'visit_type': 'OP', 'diagnosis_codes': 'G45.9', 'procedure_codes': ' ', 'billed_amount': '1500.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5007', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'TIA evaluation.'}
# {'patient_id': 'P062', 'name': 'Grace Park', 'dob': '2001-04-04', 'gender': 'F', 'contact': '7000056666', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-27', 'visit_type': 'OP', 'diagnosis_codes': 'A09', 'procedure_codes': ' ', 'billed_amount': '800.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7007', 'payment_status': 'Paid', 'discharge_date': '2025-10-27', 'follow_up_required': 'No', 'notes': 'Stomach upset; fluids advised.'}
# {'patient_id': 'P063', 'name': 'Rajiv Menon', 'dob': '1958-12-12', 'gender': 'M', 'contact': '9810033333', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-27', 'visit_type': 'IP', 'diagnosis_codes': 'I21.0', 'procedure_codes': 'PROC1010', 'billed_amount': '23000.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1010', 'payment_status': 'Paid', 'discharge_date': '2025-10-30', 'follow_up_required': 'Yes', 'notes': 'PCI performed.'}
# {'patient_id': 'P064', 'name': 'Sylvia Plath', 'dob': '1932-10-27', 'gender': 'F', 'contact': '7700018888', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-28', 'visit_type': 'OP', 'diagnosis_codes': 'R53.1', 'procedure_codes': ' ', 'billed_amount': '600.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3010', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Elderly fatigue management.'}
# {'patient_id': 'P065', 'name': 'Marcus Aurelius', 'dob': '1975-04-04', 'gender': 'M', 'contact': '9990022222', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-28', 'visit_type': 'IP', 'diagnosis_codes': 'C50.9', 'procedure_codes': 'PROC6011', 'billed_amount': '34000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6007', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Breast surgery.'}
# {'patient_id': 'P066', 'name': 'Hannah Wells', 'dob': '1990-11-11', 'gender': 'F', 'contact': '7700024444', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-28', 'visit_type': 'OP', 'diagnosis_codes': 'H66.9', 'procedure_codes': ' ', 'billed_amount': '2700.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4011', 'payment_status': 'Paid', 'discharge_date': '2025-10-28', 'follow_up_required': 'No', 'notes': 'Chronic OM follow-up.'}
# {'patient_id': 'P067', 'name': 'Victor Cruz', 'dob': '1988-02-02', 'gender': 'M', 'contact': '7000077777', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-10-29', 'visit_type': 'OP', 'diagnosis_codes': 'S72.1', 'procedure_codes': 'PROC2008', 'billed_amount': '6400.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2010', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Hip fracture review.'}
# {'patient_id': 'P068', 'name': 'Nina Simone', 'dob': '1958-02-21', 'gender': 'F', 'contact': '7700034444', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-10-29', 'visit_type': 'OP', 'diagnosis_codes': 'E03.9', 'procedure_codes': ' ', 'billed_amount': '3800.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8007', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Thyroid labs abnormal.'}
# {'patient_id': 'P069', 'name': 'Omar Sy', 'dob': '1980-01-01', 'gender': 'M', 'contact': '8800056666', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-29', 'visit_type': 'OP', 'diagnosis_codes': 'G43.0', 'procedure_codes': 'PROC3007', 'billed_amount': '5900.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5008', 'payment_status': 'Paid', 'discharge_date': '2025-10-29', 'follow_up_required': 'Yes', 'notes': 'Cluster headache treatment.'}
# {'patient_id': 'P070', 'name': 'Leah Baker', 'dob': '2006-07-07', 'gender': 'F', 'contact': '7700035556', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-10-30', 'visit_type': 'OP', 'diagnosis_codes': 'A15.0', 'procedure_codes': ' ', 'billed_amount': '1000.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7008', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'TB follow-up.'}
# {'patient_id': 'P071', 'name': 'Harish Rao', 'dob': '1963-03-03', 'gender': 'M', 'contact': '9810055555', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-10-30', 'visit_type': 'OP', 'diagnosis_codes': 'I25.10', 'procedure_codes': 'PROC1011', 'billed_amount': '13200.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1011', 'payment_status': 'Paid', 'discharge_date': '2025-10-30', 'follow_up_required': 'Yes', 'notes': 'Stable CAD follow-up.'}
# {'patient_id': 'P072', 'name': 'Sonia Kapoor', 'dob': '1984-12-12', 'gender': 'F', 'contact': '7700067777', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-10-30', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '1700.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3011', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Diabetes review.'}
# {'patient_id': 'P073', 'name': 'Neil Armstrong', 'dob': '1930-08-05', 'gender': 'M', 'contact': '7000088888', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-10-31', 'visit_type': 'IP', 'diagnosis_codes': 'C34.9', 'procedure_codes': 'PROC6012', 'billed_amount': '47000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6008', 'payment_status': 'Paid', 'discharge_date': '2025-11-10', 'follow_up_required': 'Yes', 'notes': 'Complex oncology admission.'}
# {'patient_id': 'P074', 'name': 'Maya Angelou', 'dob': '1928-04-04', 'gender': 'F', 'contact': '7700091112', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-10-31', 'visit_type': 'OP', 'diagnosis_codes': 'G93.4', 'procedure_codes': ' ', 'billed_amount': '3300.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5009', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Dementia evaluation.'}
# {'patient_id': 'P075', 'name': 'Rajeshwari Pillai', 'dob': '1979-09-09', 'gender': 'F', 'contact': '8800067777', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-10-31', 'visit_type': 'OP', 'diagnosis_codes': 'H92.2', 'procedure_codes': 'PROC5008', 'billed_amount': '2900.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4012', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Post-op ENT check.'}
# {'patient_id': 'P076', 'name': 'Daniel Ortega', 'dob': '1982-11-11', 'gender': 'M', 'contact': '7700092222', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-11-01', 'visit_type': 'OP', 'diagnosis_codes': 'M25.5', 'procedure_codes': ' ', 'billed_amount': '2300.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2011', 'payment_status': 'Paid', 'discharge_date': '2025-11-01', 'follow_up_required': 'No', 'notes': 'Knee pain conservative care.'}
# {'patient_id': 'P077', 'name': 'Linda Nguyen', 'dob': '1994-04-04', 'gender': 'F', 'contact': '6000093333', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-11-01', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': 'PROC8002', 'billed_amount': '4300.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8008', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Diabetes insulin start.'}
# {'patient_id': 'P078', 'name': 'Mark Ruffalo', 'dob': '1967-11-22', 'gender': 'M', 'contact': '7700083333', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-11-02', 'visit_type': 'OP', 'diagnosis_codes': 'I48.1', 'procedure_codes': 'PROC1012', 'billed_amount': '9400.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1012', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Arrhythmia consult.'}
# {'patient_id': 'P079', 'name': 'Aditi Rao', 'dob': '1999-01-01', 'gender': 'F', 'contact': '7700084444', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-11-02', 'visit_type': 'OP', 'diagnosis_codes': 'R53.8', 'procedure_codes': ' ', 'billed_amount': '700.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3012', 'payment_status': 'Paid', 'discharge_date': '2025-11-02', 'follow_up_required': 'No', 'notes': 'General check-up.'}
# {'patient_id': 'P080', 'name': 'Chen Li', 'dob': '1986-06-06', 'gender': 'M', 'contact': '6000094444', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-11-02', 'visit_type': 'OP', 'diagnosis_codes': 'H65.1', 'procedure_codes': 'PROC5009', 'billed_amount': '3050.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4013', 'payment_status': 'Paid', 'discharge_date': '2025-11-02', 'follow_up_required': 'No', 'notes': 'Ear procedure.'}
# {'patient_id': 'P081', 'name': 'Olivia Wilde', 'dob': '1984-03-10', 'gender': 'F', 'contact': '7700085555', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-11-03', 'visit_type': 'OP', 'diagnosis_codes': 'A09', 'procedure_codes': ' ', 'billed_amount': '900.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7009', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Viral illness.'}
# {'patient_id': 'P082', 'name': 'Pranav Joshi', 'dob': '1992-02-02', 'gender': 'M', 'contact': '9810066666', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-11-03', 'visit_type': 'OP', 'diagnosis_codes': 'G43.1', 'procedure_codes': 'PROC3008', 'billed_amount': '6100.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5010', 'payment_status': 'Paid', 'discharge_date': '2025-11-03', 'follow_up_required': 'Yes', 'notes': 'Migraine infusion.'}
# {'patient_id': 'P083', 'name': 'Samanta Fox', 'dob': '1980-05-05', 'gender': 'F', 'contact': '7700079999', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-11-03', 'visit_type': 'IP', 'diagnosis_codes': 'C18.9', 'procedure_codes': 'PROC6013', 'billed_amount': '36000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6009', 'payment_status': 'Pending', 'discharge_date': '2025-11-08', 'follow_up_required': 'Yes', 'notes': 'Oncology multi-day admission.'}
# {'patient_id': 'P084', 'name': 'Imelda Marcos', 'dob': '1934-07-02', 'gender': 'F', 'contact': '7700069999', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-11-04', 'visit_type': 'OP', 'diagnosis_codes': 'I10', 'procedure_codes': ' ', 'billed_amount': '1500.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3013', 'payment_status': 'Paid', 'discharge_date': '2025-11-04', 'follow_up_required': 'No', 'notes': 'BP control.'}
# {'patient_id': 'P085', 'name': 'Diego Rivera', 'dob': '1905-12-08', 'gender': 'M', 'contact': '8800007777', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-11-04', 'visit_type': 'OP', 'diagnosis_codes': 'I21.9', 'procedure_codes': 'PROC1013', 'billed_amount': '15500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1013', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Post-MI monitoring.'}
# {'patient_id': 'P086', 'name': 'Aisha Siddiqui', 'dob': '1998-09-09', 'gender': 'F', 'contact': '9810077777', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-11-05', 'visit_type': 'OP', 'diagnosis_codes': 'H91.2', 'procedure_codes': ' ', 'billed_amount': '2400.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4014', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Hearing loss eval.'}
# {'patient_id': 'P087', 'name': 'Brian Cox', 'dob': '1968-06-01', 'gender': 'M', 'contact': '7700059999', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-11-05', 'visit_type': 'OP', 'diagnosis_codes': 'G45.9', 'procedure_codes': 'PROC3009', 'billed_amount': '1700.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5011', 'payment_status': 'Paid', 'discharge_date': '2025-11-05', 'follow_up_required': 'No', 'notes': 'Stroke follow-up.'}
# {'patient_id': 'P088', 'name': 'Helene Fischer', 'dob': '1984-10-05', 'gender': 'F', 'contact': '7000095555', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-11-05', 'visit_type': 'OP', 'diagnosis_codes': 'E03.9', 'procedure_codes': ' ', 'billed_amount': '4100.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8010', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Thyroid follow-up.'}
# {'patient_id': 'P089', 'name': 'Anil Kapoor', 'dob': '1959-12-24', 'gender': 'M', 'contact': '9900094444', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-11-06', 'visit_type': 'OP', 'diagnosis_codes': 'S32.0', 'procedure_codes': 'PROC2010', 'billed_amount': '7200.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2012', 'payment_status': 'Paid', 'discharge_date': '2025-11-06', 'follow_up_required': 'Yes', 'notes': 'Spine surgery follow-up.'}
# {'patient_id': 'P090', 'name': 'Molly Ringwald', 'dob': '1968-02-18', 'gender': 'F', 'contact': '7700041111', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-11-06', 'visit_type': 'OP', 'diagnosis_codes': 'A08.5', 'procedure_codes': ' ', 'billed_amount': '1100.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7010', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Pediatric GI.'}
# {'patient_id': 'P091', 'name': 'Yusuf Pathan', 'dob': '1982-10-22', 'gender': 'M', 'contact': '9810088888', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-11-07', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '1900.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3014', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Diabetes counselling.'}
# {'patient_id': 'P092', 'name': 'Nicole Kidman', 'dob': '1967-06-20', 'gender': 'F', 'contact': '7700021111', 'provider_id': 'DR100', 'provider_name': 'Dr. Mehta', 'department': 'Cardiology', 'visit_date': '2025-11-07', 'visit_type': 'OP', 'diagnosis_codes': 'I50.9', 'procedure_codes': 'PROC1014', 'billed_amount': '21000.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS1014', 'payment_status': 'Paid', 'discharge_date': '2025-11-07', 'follow_up_required': 'Yes', 'notes': 'CHF management.'}
# {'patient_id': 'P093', 'name': 'Raj Malhotra', 'dob': '1974-01-15', 'gender': 'M', 'contact': '7700010001', 'provider_id': 'DR500', 'provider_name': 'Dr. Gupta', 'department': 'ENT', 'visit_date': '2025-11-07', 'visit_type': 'OP', 'diagnosis_codes': 'H65.9', 'procedure_codes': ' ', 'billed_amount': '2500.00', 'insurance_provider': 'MedSecure', 'insurance_id': 'INS4015', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Ear pain.'}
# {'patient_id': 'P094', 'name': 'Tara Strong', 'dob': '1986-02-12', 'gender': 'F', 'contact': '7000019999', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-11-08', 'visit_type': 'OP', 'diagnosis_codes': 'G93.3', 'procedure_codes': 'PROC3010', 'billed_amount': '4900.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5012', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Neurology consult.'}
# {'patient_id': 'P095', 'name': 'Victor Hugo Jr', 'dob': '2000-08-08', 'gender': 'M', 'contact': '7700002222', 'provider_id': 'DR600', 'provider_name': 'Dr. Rao', 'department': 'Oncology', 'visit_date': '2025-11-08', 'visit_type': 'IP', 'diagnosis_codes': 'C34.1', 'procedure_codes': 'PROC6014', 'billed_amount': '29000.00', 'insurance_provider': 'CancerCover', 'insurance_id': 'INS6010', 'payment_status': 'Paid', 'discharge_date': '2025-11-15', 'follow_up_required': 'Yes', 'notes': 'Chemotherapy session.'}
# {'patient_id': 'P096', 'name': 'Ritika Sen', 'dob': '1995-09-09', 'gender': 'F', 'contact': '7700003333', 'provider_id': 'DR400', 'provider_name': 'Dr. Khan', 'department': 'General Medicine', 'visit_date': '2025-11-09', 'visit_type': 'OP', 'diagnosis_codes': 'R10.9', 'procedure_codes': ' ', 'billed_amount': '850.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS3015', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Abdominal pain.'}
# {'patient_id': 'P097', 'name': 'Dominic Toretto', 'dob': '1980-03-03', 'gender': 'M', 'contact': '8800090000', 'provider_id': 'DR200', 'provider_name': 'Dr. Iyer', 'department': 'Orthopedics', 'visit_date': '2025-11-09', 'visit_type': 'OP', 'diagnosis_codes': 'M17.1', 'procedure_codes': 'PROC2011', 'billed_amount': '6800.00', 'insurance_provider': 'HealthPlus', 'insurance_id': 'INS2013', 'payment_status': 'Paid', 'discharge_date': '2025-11-09', 'follow_up_required': 'Yes', 'notes': 'Knee arthroscopy.'}
# {'patient_id': 'P098', 'name': 'Sasha Banks', 'dob': '1992-12-01', 'gender': 'F', 'contact': '7700091113', 'provider_id': 'DR700', 'provider_name': 'Dr. Fernandez', 'department': 'Pediatrics', 'visit_date': '2025-11-10', 'visit_type': 'OP', 'diagnosis_codes': 'A09', 'procedure_codes': ' ', 'billed_amount': '950.00', 'insurance_provider': 'ChildCare', 'insurance_id': 'INS7011', 'payment_status': 'Pending', 'discharge_date': ' ', 'follow_up_required': 'No', 'notes': 'Viral gastro.'}
# {'patient_id': 'P099', 'name': 'Igor Kravitz', 'dob': '1977-01-01', 'gender': 'M', 'contact': '6000015555', 'provider_id': 'DR300', 'provider_name': 'Dr. Lee', 'department': 'Neurology', 'visit_date': '2025-11-10', 'visit_type': 'OP', 'diagnosis_codes': 'G43.0', 'procedure_codes': 'PROC3011', 'billed_amount': '5900.00', 'insurance_provider': 'GlobalCare', 'insurance_id': 'INS5013', 'payment_status': 'Unpaid', 'discharge_date': ' ', 'follow_up_required': 'Yes', 'notes': 'Severe migraine.'}
# {'patient_id': 'P100', 'name': 'Ankita Sharma', 'dob': '1994-04-04', 'gender': 'F', 'contact': '9810090000', 'provider_id': 'DR800', 'provider_name': 'Dr. Sinha', 'department': 'Endocrinology', 'visit_date': '2025-11-10', 'visit_type': 'OP', 'diagnosis_codes': 'E11.9', 'procedure_codes': ' ', 'billed_amount': '4200.00', 'insurance_provider': 'EndoCare', 'insurance_id': 'INS8011', 'payment_status': 'Paid', 'discharge_date': '2025-11-10', 'follow_up_required': 'No', 'notes': 'Sugar levels controlled.'}

# Data Cleaning Completed Successfully!

# pending_payments.csv created successfully.
# patient_summary.csv created successfully.

# --- Summary Report ---
# Total rows read: 100
# Processed rows: 100
# Skipped rows: 0
# Pending payments: 54
# Patient summary rows: 100

