# Import required modules
from typing import Optional
from datetime import date, datetime
from pydantic import Field, BaseModel

# -------------------------------
# Asset Model Definition
# -------------------------------
class Asset(BaseModel):
    # Unique identifier for the asset (optional, usually auto-generated by DB)
    asset_id: Optional[int] = None
    
    # Unique tag for the asset (e.g., "UST-1001")
    asset_tag: str
    
    # Type of asset (Laptop, Monitor, Keyboard, etc.)
    asset_type: str = Field(..., description="Enter in proper format")
    
    # Serial number of the asset
    serial_number: str = Field(..., description="Enter in proper format")
    
    # Manufacturer name (Dell, HP, Lenovo, etc.)
    manufacturer: str = Field(..., description="Enter in proper format")
    
    # Model name of the asset
    model: str = Field(..., description="Enter in proper format")
    
    # Date of purchase
    purchase_date: date = Field(..., description="Enter in proper format")
    
    # Warranty period in years
    warranty_years: int = Field(..., description="Enter in proper format")
    
    # Person to whom the asset is assigned (optional)
    assigned_to: Optional[str] = None
    
    # Current status of the asset (Available, Assigned, Retired, Repair, etc.)
    asset_status: str = Field(..., description="Enter in proper format")
    
    # Last updated timestamp (defaults to current time when object is created)
    last_updated: Optional[datetime] = Field(
        default_factory=datetime.now,
        description="Enter in proper format"
    )

# -------------------------------
# Sample Object Creation
# -------------------------------
# sample_asset = Asset(
#     asset_tag="UST-1001",
#     asset_type="Laptop",
#     serial_number="SN123456789",
#     manufacturer="Dell",
#     model="Latitude 5420",
#     purchase_date=date(2023, 5, 20),
#     warranty_years=3,
#     assigned_to="Shyam Sunder",
#     asset_status="Assigned"
# )

# Print the sample object
# print(sample_asset)

# -------------------------------
# Expected Output
# -------------------------------
# asset_id=None asset_tag='UST-1001' asset_type='Laptop' serial_number='SN123456789'
# manufacturer='Dell' model='Latitude 5420' purchase_date=datetime.date(2023, 5, 20)
# warranty_years=3 assigned_to='Shyam Sunder' asset_status='Assigned'
# last_updated=datetime.datetime(2025, 11, 26, 17, 28, 45, 123456)
