from pydantic import BaseModel, validator
from datetime import date
import re
from typing import Optional

# Define the MaintenanceModel class for validating maintenance log data
class MaintenanceModel(BaseModel):
    log_id: Optional[int] = None  # Optional log ID, generated by the database if not provided
    asset_tag: str  # Asset tag for the item being maintained
    maintenance_type: str  # Type of maintenance (e.g., Repair, Service, Upgrade)
    vendor_name: str  # Name of the vendor providing the maintenance
    description: str  # Detailed description of the maintenance performed
    cost: float  # Cost of the maintenance
    maintenance_date: date  # Date when the maintenance was performed
    technician_name: str  # Name of the technician performing the maintenance
    status: str  # Status of the maintenance (Completed or Pending)

    # Validator for asset_tag: It must follow the 'UST-XXX-0000' format
    @validator('asset_tag')
    def validate_asset_tag(cls, v):
        if not re.match(r'^UST-[A-Z]{3}-\d{4}$', v):  # Matches the UST-XXX-0000 format
            raise ValueError('Asset tag must follow UST-XXX-0000 format')
        return v
    
    # Validator for maintenance_type: It must be one of Repair, Service, or Upgrade
    @validator('maintenance_type')
    def validate_maintenance_type(cls, v):
        allowed_types = ["Repair", "Service", "Upgrade"]  # List of allowed maintenance types
        if v not in allowed_types:
            raise ValueError(f'Maintenance type must be one of {allowed_types}')
        return v
    
    # Validator for vendor_name: It must contain only alphabets (no digits or special characters)
    @validator('vendor_name')
    def validate_vendor_name(cls, v):
        if not re.match(r'^[A-Za-z ]+$', v):  # Matches only alphabetic characters and spaces
            raise ValueError('Vendor name must contain only alphabets')
        return v
    
    # Validator for description: It must be at least 10 characters long
    @validator('description')
    def validate_description(cls, v):
        if not v or len(v.strip()) < 10:  # Checks if description is empty or less than 10 characters
            raise ValueError('Description must be at least 10 characters long')
        return v
    
    # Validator for cost: It must be greater than 0 and have at most 2 decimal places
    @validator('cost')
    def validate_cost(cls, v):
        if v <= 0:  # Ensures that cost is positive
            raise ValueError('Cost must be greater than 0')
        
        if round(v, 2) != v:  # Ensures that the cost has at most two digits after the decimal
            raise ValueError('Cost must have at most two digits after decimal')
        return v
    
    # Validator for maintenance_date: It must not be in the future
    @validator('maintenance_date')
    def validate_maintenance_date(cls, v):
        if v > date.today():  # Ensures that the maintenance date is not in the future
            raise ValueError('Maintenance date cannot be in the future')
        return v
    
    # Validator for technician_name: It must contain only alphabets
    @validator('technician_name')
    def validate_technician_name(cls, v):
        if not re.match(r'^[A-Za-z ]+$', v):  # Matches only alphabetic characters and spaces
            raise ValueError('Technician name must contain only alphabets')
        return v
    
    # Validator for status: It must be either "Completed" or "Pending"
    @validator('status')
    def validate_status(cls, v):
        if v not in ["Completed", "Pending"]:  # Ensures that the status is valid
            raise ValueError('Status must be either Completed or Pending')
        return v
    
    # Configuration settings for the model
    class Config:
        min_anystr_length = 1  # Ensures that string fields have at least one character (non-empty)
        anystr_strip_whitespace = True  # Strips leading and trailing spaces from all string fields
