from pydantic import BaseModel, field_validator, model_validator
from datetime import date, datetime
import re

class AssetInventory(BaseModel):
    # Asset attributes with optional fields for asset_id, assigned_to, and last_updated.
    asset_id: int | None = None  # Optional, generated by DB
    asset_tag: str  # Unique identifier, must start with "UST-"
    asset_type: str  # Type of asset (e.g., Laptop, Desktop)
    serial_number: str  # Serial number, must match specific format
    manufacturer: str  # Manufacturer name (e.g., Dell, HP)
    model: str  # Model of the asset
    purchase_date: date  # Date of purchase
    warranty_years: int  # Warranty period in years (between 1 and 5)
    condition_status: str  # Condition of the asset (e.g., New, Used)
    assigned_to: str | None = None  # Optional field to assign asset
    location: str  # Location where the asset is stored (e.g., TVM, Bangalore)
    asset_status: str  # Status of the asset (e.g., Available, Assigned)
    last_updated: datetime | None = None  # Optional, auto-set in DB

    # Validator for asset_tag: Ensures it starts with 'UST-'
    @field_validator("asset_tag")
    def tag_must_start_with_ust(cls, v):
        if not v.startswith("UST-"):
            raise ValueError("asset_tag must start with UST")
        return v

    # Validator for serial_number: Ensures it follows 'SN-XX-12345' format
    @field_validator("serial_number")
    def serial_number_valid(cls, v):
        if not re.fullmatch(r"SN-[A-Z]{2,3}-\d{5}", v):
            raise ValueError("Invalid Serial Number.")
        return v

    # Validator for manufacturer: Ensures the manufacturer is valid
    @field_validator("manufacturer")
    def manufacturer_valid(cls, v):
        valid = {"Dell", "HP", "Lenovo", "Samsung", "LG"}
        if v not in valid:
            raise ValueError("Invalid manufacturer")
        return v

    # Validator for warranty_years: Ensures warranty is between 1 and 5 years
    @field_validator("warranty_years")
    def warranty_range(cls, v):
        if not (1 <= v <= 5):
            raise ValueError("warranty_years must be between 1 and 5")
        return v

    # Validator for condition_status: Ensures valid condition options
    @field_validator("condition_status")
    def condition_valid(cls, v):
        valid = {"New", "Good", "Used", "Damaged", "Fair"}
        if v not in valid:
            raise ValueError("Invalid condition_status")
        return v

    # Validator for location: Ensures asset location is one of the allowed cities
    @field_validator("location")
    def location_valid(cls, v):
        valid = {"TVM", "Bangalore", "Chennai", "Hyderabad", "Trivandrum"}
        if v not in valid:
            raise ValueError("Invalid location")
        return v

    # Validator for asset_status: Ensures the status is valid
    @field_validator("asset_status")
    def status_valid(cls, v):
        valid = {"Available", "Assigned", "Repair", "Retired"}
        if v not in valid:
            raise ValueError("Invalid asset_status")
        return v

    # After model validation: Checks that the purchase_date is not in the future
    @model_validator(mode="after")
    def check_purchase_date(cls, values):
        if values.purchase_date > date.today():
            raise ValueError("purchase_date cannot be in the future")
        return values
