from typing import Optional
from datetime import date
from pydantic import BaseModel, ValidationError
import re
import csv

# Employee model definition using Pydantic for schema validation and type enforcement
class Employee(BaseModel):
    emp_id: Optional[int] = None   # Auto-increment primary key (optional, generated by DB)
    emp_code: str                  # Employee code, must follow "USTEMP-XXXX" format
    full_name: str                 # Full name, alphabets and spaces only
    email: str                     # Corporate email, must end with @ust.com
    phone: str                     # 10-digit Indian mobile number starting with 6–9
    department: str                # Department (HR, IT, Admin, Finance, Support)
    location: str                  # Office location (Trivandrum, Bangalore, etc.)
    join_date: date                # Date of joining, cannot be in the future
    status: str                    # Employment status (Active, Inactive, Resigned)


# Function: Validate employee fields against business rules
def validate_employee(employee: Employee) -> list[str]:
    errors = []

    # Employee code must start with "USTEMP-" followed by alphanumeric characters
    if not re.match(r"^USTEMP-[A-Za-z0-9]*$", employee.emp_code):
        errors.append(f"Invalid emp_code: {employee.emp_code}")

    # Full name must contain only alphabets and spaces
    if not re.match(r"^[A-Za-z ]+$", employee.full_name):
        errors.append("Full name must contain only alphabets and spaces")

    # Email must belong to corporate domain
    if not employee.email.endswith("@ust.com"):
        errors.append("Email must end with @ust.com")

    # Phone must be a valid 10-digit Indian mobile number
    if not re.match(r"^[6-9]\d{9}$", employee.phone):
        errors.append("Phone must be a valid 10-digit Indian mobile number")

    # Department must be one of the allowed values
    allowed_departments = ["HR", "IT", "Admin", "Finance", "Support"]
    if employee.department not in allowed_departments:
        errors.append(f"Invalid department: {employee.department}")

    # Location must be one of the allowed office locations
    allowed_locations = ["Trivandrum", "Bangalore", "Chennai", "Hyderabad", "Kochi"]
    if employee.location not in allowed_locations:
        errors.append(f"Invalid location: {employee.location}")

    # Join date cannot be in the future
    if employee.join_date > date.today():
        errors.append("Join date cannot be in the future")

    # Status must be one of the allowed values
    allowed_status = ["Active", "Inactive", "Resigned"]
    if employee.status not in allowed_status:
        errors.append(f"Invalid status: {employee.status}")

    return errors

