from pydantic import BaseModel, Field, EmailStr
from typing import Optional

# VendorMaster model definition using Pydantic for schema validation and type enforcement
class VendorMaster(BaseModel):
    vendor_id: Optional[int] = None   # Auto-increment primary key (optional, generated by DB)
    vendor_name: str = Field(..., max_length=100, pattern=r"^[A-Za-z ]+$")   # Vendor name, alphabets and spaces only
    contact_person: str = Field(..., max_length=100, pattern=r"^[A-Za-z ]+$") # Contact person name, alphabets and spaces only
    contact_phone: str = Field(..., pattern=r"^[6-9]\d{9}$")  # Valid 10-digit Indian mobile number starting with 6–9
    gst_number: str = Field(..., min_length=15, max_length=15, pattern=r"^[A-Za-z0-9]{15}$") # GST number, exactly 15 alphanumeric characters
    email: EmailStr   # Valid email address format enforced by Pydantic
    address: Optional[str] = Field(None, max_length=200)  # Optional address, max length 200 characters
    city: str         # City where vendor is located
    active_status: str # Vendor status (Active/Inactive)


# Function: Validate vendor fields against business rules
def validate(vendor: VendorMaster) -> bool:
    # Approved cities where vendors can be registered
    approved = ["Trivandrum", "Bangalore", "Chennai", "Hyderabad", "Mumbai", "Pune", "Kolkata"]
    if vendor.city not in approved:
        return False

    # Active status must be either "Active" or "Inactive"
    if vendor.active_status not in ["Active", "Inactive"]:
        return False

    # Return True if all validations pass
    return True
